package com.animakerpro.app

import android.app.Activity
import android.app.AlertDialog
import android.graphics.Color
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.view.Gravity
import android.view.View
import android.widget.*

class MainActivity : Activity() {
    private lateinit var document: AnimationDocument
    private lateinit var canvasView: NativeCanvasView
    private lateinit var rulerOverlay: RulerOverlayView
    private lateinit var timeline: TimelineView
    private val handler=Handler(Looper.getMainLooper()); private var playing=false
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);document=AnimationDocument();val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.rgb(17,19,24))};root.addView(toolbar(),LinearLayout.LayoutParams(-1,dp(52)));val host=FrameLayout(this).apply{setBackgroundColor(Color.rgb(235,235,235))};canvasView=NativeCanvasView(this);rulerOverlay=RulerOverlayView(this);host.addView(canvasView,FrameLayout.LayoutParams(-1,-1));host.addView(rulerOverlay,FrameLayout.LayoutParams(-1,-1));root.addView(host,LinearLayout.LayoutParams(-1,0,1f));val scroll=HorizontalScrollView(this).apply{setBackgroundColor(Color.rgb(23,25,30));isHorizontalScrollBarEnabled=true};timeline=TimelineView(this).apply{document=this@MainActivity.document;onFrameSelected={i->document.select(i);canvasView.setFrame(i);refresh()};onFrameLongPressed={i->showFrameActions(i)}};scroll.addView(timeline,HorizontalScrollView.LayoutParams(-1,dp(118)));root.addView(scroll);root.addView(animationControls(),LinearLayout.LayoutParams(-1,dp(48)));setContentView(root)}
    private fun toolbar():View=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(4),0,dp(4),0);setBackgroundColor(Color.rgb(24,27,33));addButton("☰"){showInfo("AnimakerPro","Canvas nativo C++ • frame-by-frame • rig em desenvolvimento")};addButton("🖌"){showBrushSettings()};addButton("⌫"){showInfo("Borracha","O modo borracha usará o mesmo pipeline nativo do pincel.")};addButton("▱"){showInfo("Balde","Fill engine nativo será conectado ao raster core.")};addButton("⌁"){showInfo("Laço","Seleção raster/vetorial está no próximo módulo de ferramentas.")};addButton("◉"){showInfo("Seletor de cor","Color picker nativo será conectado ao framebuffer.")};addButton("⌖"){showRulerPicker()};addButton("◌"){canvasView.onionSkin=!canvasView.onionSkin;canvasView.invalidate()};addView(Space(this),LinearLayout.LayoutParams(0,-1,1f));addButton("＋"){addFrame()};addButton("▣"){duplicateFrame()};addButton("▤"){showFramesViewer()}}
    private fun animationControls():View=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(4),0,dp(4),0);setBackgroundColor(Color.rgb(20,22,27));addButton("|◀"){document.select(0);canvasView.setFrame(0);refresh()};addButton("◀"){document.select(document.currentFrame-1);canvasView.setFrame(document.currentFrame);refresh()};addButton(if(playing)"■" else "▶"){togglePlayback()};addButton("▶"){document.select(document.currentFrame+1);canvasView.setFrame(document.currentFrame);refresh()};addButton("▶|"){document.select(document.frames.lastIndex);canvasView.setFrame(document.currentFrame);refresh()};addButton("+ Frame"){addFrame()};addButton("Clone"){duplicateFrame()};addButton("Loop"){makeLoop()}}
    private fun showBrushSettings(){val p=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(20),dp(8),dp(20),0)};val sl=TextView(this).apply{text="Tamanho: ${canvasView.brushSize.toInt()} px";setTextColor(Color.WHITE)};val s=SeekBar(this).apply{max=199;progress=canvasView.brushSize.toInt()-1};s.setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(x:SeekBar?,v:Int,u:Boolean){canvasView.brushSize=(v+1).toFloat();sl.text="Tamanho: ${v+1} px"};override fun onStartTrackingTouch(x:SeekBar?){};override fun onStopTrackingTouch(x:SeekBar?){}});val ol=TextView(this).apply{text="Opacidade: ${(canvasView.brushOpacity*100).toInt()}%";setTextColor(Color.WHITE)};val o=SeekBar(this).apply{max=100;progress=(canvasView.brushOpacity*100).toInt()};o.setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(x:SeekBar?,v:Int,u:Boolean){canvasView.brushOpacity=(v.coerceAtLeast(1)/100f);ol.text="Opacidade: ${v.coerceAtLeast(1)}%"};override fun onStartTrackingTouch(x:SeekBar?){};override fun onStopTrackingTouch(x:SeekBar?){}});val stl=TextView(this).apply{text="Estabilização: ${(canvasView.stabilization*100).toInt()}%";setTextColor(Color.WHITE)};val st=SeekBar(this).apply{max=90;progress=(canvasView.stabilization*100).toInt()};st.setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(x:SeekBar?,v:Int,u:Boolean){canvasView.stabilization=v/100f;stl.text="Estabilização: $v%"};override fun onStartTrackingTouch(x:SeekBar?){};override fun onStopTrackingTouch(x:SeekBar?){}});val pr=CheckBox(this).apply{text="Pressão / espessura dinâmica";isChecked=canvasView.pressureSensitivity;setTextColor(Color.WHITE)};pr.setOnCheckedChangeListener{_,v->canvasView.pressureSensitivity=v};p.addView(sl);p.addView(s);p.addView(ol);p.addView(o);p.addView(stl);p.addView(st);p.addView(pr);AlertDialog.Builder(this).setTitle("Pincel C++").setView(p).setPositiveButton("OK",null).show()}
    private fun showRulerPicker(){val m=RulerOverlayView.Mode.values();val l=m.map{it.name.replace('_',' ')}.toTypedArray();AlertDialog.Builder(this).setTitle("Réguas").setSingleChoiceItems(l,m.indexOf(rulerOverlay.mode)){d,w->rulerOverlay.mode=m[w];d.dismiss()}.show()}
    private fun addFrame(){val i=document.currentFrame+1;document.addBlank(document.currentFrame);canvasView.insertFrame(i);canvasView.setFrame(i);refresh()}
    private fun duplicateFrame(){val s=document.currentFrame;val i=document.duplicate(s);canvasView.duplicateFrame(s,i);canvasView.setFrame(i);refresh()}
    private fun makeLoop(){if(document.frames.size<2)return;val e=document.frames.lastIndex;document.makeLoop(0,e);canvasView.makeLoop(0,e);canvasView.setFrame(document.currentFrame);refresh()}
    private fun togglePlayback(){playing=!playing;if(playing)playNext()else handler.removeCallbacksAndMessages(null)}
    private fun playNext(){if(!playing||document.frames.isEmpty())return;document.select((document.currentFrame+1)%document.frames.size);canvasView.setFrame(document.currentFrame);refresh();handler.postDelayed({playNext()},1000L/document.fps)}
    private fun showFrameActions(i:Int){val a=arrayOf("Selecionar","Duplicar","Excluir","Limpar desenho");AlertDialog.Builder(this).setTitle("Quadro ${i+1}").setItems(a){_,w->when(w){0->document.select(i);1->{document.select(i);duplicateFrame()};2->if(document.frames.size>1){document.select(i);document.remove(i);canvasView.removeFrame(i)};3->{document.select(i);canvasView.clearCurrentFrame()}};canvasView.setFrame(document.currentFrame);refresh()}.show()}
    private fun showFramesViewer(){val s=BooleanArray(document.frames.size);val l=document.frames.indices.map{"Quadro ${it+1}"}.toTypedArray();AlertDialog.Builder(this).setTitle("Visualizador de quadros").setMultiChoiceItems(l,s){_,i,c->s[i]=c}.setNegativeButton("Fechar",null).setPositiveButton("Duplicar seleção",null).show()}
    private fun showInfo(t:String,m:String)=AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("OK",null).show()
    private fun refresh(){canvasView.invalidate();timeline.invalidate()}
    private fun LinearLayout.addButton(label:String,action:()->Unit){addView(Button(this@MainActivity).apply{text=label;setTextColor(Color.WHITE);setOnClickListener{action()};minWidth=0;minimumWidth=0;setPadding(dp(2),0,dp(2),0)},LinearLayout.LayoutParams(dp(48),-1))}
    private fun dp(v:Int)= (v*resources.displayMetrics.density).toInt()
}
